# Configuration schema for sms_valid module

sms_valid.settings:
  type: config_object
  label: 'SMS Valid Settings'
  mapping:
    use_rulesets:
      type: integer
      label: 'Use rulesets'
    use_global_ruleset:
      type: integer
      label: 'Use global ruleset'
    global_ruleset:
      type: integer
      label: 'Use rulesets'
    local_number_prefix:
      type: integer
      label: 'Use rulesets'
    local_number_ruleset:
      type: integer
      label: 'Use rulesets'
    last_resort_enabled:
      type: integer
      label: 'Use rulesets'
    last_resort_ruleset:
      type: integer
      label: 'Use rulesets'

sms_valid.ruleset.*:
  type: config_entity
  label: 'SMS Valid ruleset'
  mapping:
    prefix:
      type: string
      label: 'Number prefix/code; 1-65535'
    name:
      type: string
      label: 'Descriptive name for this prefix/ruleset'
    dirs_enabled:
      type: integer
      label: 'Active msg directions'
    iso2:
      type: string
      label: 'ISO 3166-1 alpha-2 country code for this ruleset'
    rules:
      type: sequence
      label: 'The rules contained in this ruleset'
      sequence:
        - type: sms_valid.rule

sms_valid.rule:
  type: mapping
  label: 'SMS Valid rule'
  mapping:
    allow:
      type: boolean
      label: 'Whether to allow or reject a number based on a rule'
    comment:
      type: string
      label: 'Comment on the rule'
