# Schema for the configuration files of the SMS module.

sms.settings:
  type: mapping
  label: 'SMS Framework settings'
  mapping:
    default_gateway:
      type: string
      label: 'Default gateway for sending sms'
    bootstrap_queue:
      type: sequence
      label: 'Bootstrap Queue'
    enabled_carriers:
      type: sequence
      label: 'Enabled Carriers'
    country_codes:
      type: sequence
      label: 'International Country Codes'
      sequence:
        - type: string

# Configuration for sms gateways.
sms.gateway.*:
  type: mapping
  label: 'SMS Gateway settings'
  mapping:
    settings:
      type: sequence
      sequence:
        - type: string
