# Schema for the configuration files of the SMS module.

sms.settings:
  type: config_object
  label: 'SMS Framework settings'
  mapping:
    default_gateway:
      type: string
      label: 'Default gateway for sending sms'
    bootstrap_queue:
      type: sequence
      label: 'Bootstrap Queue'
    enabled_carriers:
      type: sequence
      label: 'Enabled Carriers'
    country_codes:
      type: sequence
      label: 'International Country Codes'
      sequence:
        - type: string

# Configuration for sms gateways.
sms.gateway.*:
  type: config_object
  label: 'SMS Gateway configuration'
  mapping:
    label:
      type: label
      label: 'Human readable gateway label'
    name:
      type: string
      label: 'Gateway machine name'
    plugin_id:
      type: string
      label: 'Gateway plugin type'
    enabled:
      type: boolean
      label: 'Gateway enabled status'
    custom:
      type: sequence
      label: 'Additional gateway-specific configuration'
      sequence:
        - type: string
