views.field.sms_number:
  type: views_field
  label: "The user's registered sms number"

views.field.sms_status:
  type: views_field
  label: 'The confirmation status of the number'

views.filter.sms_status:
  type: views.filter.in_operator
  label: 'The confirmation status of the number'
